version: '3'
services:

  spark-master:
    image: bde2020_spark-master.tar:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==<yourmasternode>"

  spark-worker-1:
    image: bde2020_spark-worker.tar:latest
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    links:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==<yourmasternode>"

  spark-worker-2:
    image: bde2020_spark-worker.tar:latest
    container_name: spark-worker-2
    ports:
      - "8082:8081"
    links:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==<yourmasternode>"
